module Ruconomic
  module API
    module CostType
      extend Ruconomic::WebService

      # Returns a cost type data object for a given cost type.
      # Parameters: entityHandle: A handle for the cost type.
      #
      # @note TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
      # @see https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=CostType_GetData
      # @return [Hash] The body content of the SOAP response.
      def self.get_data
        response = invoke('CostType_GetData') do |message|
          raise "TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
        end
      end

      # Returns cost type data objects for a given set of cost type handles.
      # Parameters: entityHandles: An array of the cost type handles.
      #
      # @note TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
      # @see https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=CostType_GetDataArray
      # @return [Hash] The body content of the SOAP response.
      def self.get_data_array
        response = invoke('CostType_GetDataArray') do |message|
          raise "TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
        end
      end

      # Gets the number of a cost type.
      # Parameters: costTypeHandle: Handle for the cost type.
      #
      # @note TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
      # @see https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=CostType_GetNumber
      # @return [Hash] The body content of the SOAP response.
      def self.get_number
        response = invoke('CostType_GetNumber') do |message|
          raise "TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
        end
      end

      # Gets the name of a cost type.
      # Parameters: costTypeHandle: Handle for the cost type.
      #
      # @note TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
      # @see https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=CostType_GetName
      # @return [Hash] The body content of the SOAP response.
      def self.get_name
        response = invoke('CostType_GetName') do |message|
          raise "TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
        end
      end

      # Gets a handle for the CostTypeGroup of a cost type.
      # Parameters: costTypeHandle: Handle for the cost type.
      #
      # @note TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
      # @see https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=CostType_GetCostTypeGroup
      # @return [Hash] The body content of the SOAP response.
      def self.get_cost_type_group
        response = invoke('CostType_GetCostTypeGroup') do |message|
          raise "TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
        end
      end

      # Gets a handle for the VAT account of a cost type.
      # Parameters: costTypeHandle: Handle for the cost type.
      #
      # @note TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
      # @see https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=CostType_GetVatAccount
      # @return [Hash] The body content of the SOAP response.
      def self.get_vat_account
        response = invoke('CostType_GetVatAccount') do |message|
          raise "TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
        end
      end

      # Return handles for all cost types.
      #
      # @note TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
      # @see https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=CostType_GetAll
      # @return [Hash] The body content of the SOAP response.
      def self.get_all
        response = invoke('CostType_GetAll') do |message|
          raise "TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
        end
      end

      # Returns a handle for the cost type with the given number.
      # Parameters: number: The number to search for.
      #
      # @note TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
      # @see https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=CostType_FindByNumber
      # @return [Hash] The body content of the SOAP response.
      def self.find_by_number
        response = invoke('CostType_FindByNumber') do |message|
          raise "TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
        end
      end

      # Returns an array with handles for cost types corresponding to the given cost type numbers. If a cost type with a given number does not exist or if no number is given then the array contains nothing at that index.
      # Parameters: numbers: The numbers to search for.
      #
      # @note TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
      # @see https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=CostType_FindByNumberList
      # @return [Hash] The body content of the SOAP response.
      def self.find_by_number_list
        response = invoke('CostType_FindByNumberList') do |message|
          raise "TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
        end
      end

      # Returns handles for the cost types with the given name.
      # Parameters: name: The name to search for.
      #
      # @note TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
      # @see https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=CostType_FindByName
      # @return [Hash] The body content of the SOAP response.
      def self.find_by_name
        response = invoke('CostType_FindByName') do |message|
          raise "TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
        end
      end

      # Return handles for all cost types from date. fromDate is based on CET. includeCalculatedProperties is reserved for future usage and should be set to false for now.
      #
      # @note TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
      # @see https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=CostType_GetAllUpdated
      # @return [Hash] The body content of the SOAP response.
      def self.get_all_updated
        response = invoke('CostType_GetAllUpdated') do |message|
          raise "TODO: This method was autogenerated from the WSDL - see https://github.com/ta/e-conomic#contributing"
        end
      end

    end
  end
end
